# Generated by Django 5.1.5 on 2025-03-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_communityresource_videolibrary_donation_livestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityresource',
            name='files',
            field=models.FileField(blank=True, upload_to='learning_files'),
        ),
    ]
