# Generated by Django 5.1.5 on 2025-03-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_communityresource_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='stream_url',
            field=models.URLField(help_text='YouTube Live URL'),
        ),
    ]
