# Generated by Django 5.1.5 on 2025-03-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_livestream_stream_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunityResource',
            new_name='Resource',
        ),
    ]
