# Generated by Django 5.1.5 on 2025-03-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_communityresource_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_url', models.URLField(help_text='YouTube or Azure Video URL')),
                ('scripture', models.TextField()),
                ('scripture_link', models.URLField(blank=True, help_text='Link to Bible Gateway search', null=True)),
                ('notes', models.TextField()),
                ('questions', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='VideoLibrary',
        ),
    ]
